PIO EQU 30H
PIC EQU 20H
N_F10 EQU 10

ORG 40
IP_F10 DW RUT_F10

ORG 1000H
MSJ DB ?
DB ?
DB ?
DB ?
FIN DB ?

ORG 3000H
RUT_F10: PUSH AX
REPT: IN AL, PIO
AND AL, 1
JNZ REPT
MOV AL, [BX]
OUT PIO+1, AL
IN AL, PIO ;PULSO STROBE
OR AL, 02H
OUT PIO, AL
IN AL, PIO
AND AL, 0FDH
OUT PIO, AL ;FIN DEL PULSO
INC BX
DEC DL
JNZ REPT
MOV AL, 20H
OUT PIC, AL
POP AX
IRET 

ORG 2000H
MOV AL, 0FEH
OUT PIC+1, AL ;PERMITIMOS LAS INT POR F10
MOV AL, N_F10
OUT PIC+4,AL ;MAPEAMOS EL VECTOR DE INT
MOV AL, 0FDH
OUT PIO+2,AL ;PIO EN MODO IMPRESORA
MOV AL, 0
OUT PIO+3, AL ;CONFIGURAMOS PB COMO SALIDA
IN AL, PIO ;TRAEMOS EL VALOR DE PA
AND AL, 0FDH ;ASEGURAMOS QUE EL VALOR DEL BIT1 SEA 0
OUT PIO, AL
MOV BX, OFFSET MSJ
MOV DL, OFFSET FIN - OFFSET MSJ
LEER: INT 6
INC BX
DEC DL
JNZ LEER
MOV BX, OFFSET MSJ
MOV DL, OFFSET FIN - OFFSET MSJ
LAZO: JMP LAZO
END